# -*- coding: utf-8 -*-
"""lavoro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYPv3br_m-9aWERNirvvOc5x6O9fYt3o
"""

#rimuovere la Ridge e utilizzare una rete neurale
#bilanciare categorie con sample
#usare bert alposto di tfidf o confronto
#fare cluster per ogni rating per vedere se ci sono outlier tra le review

import yfinance as yf
import math
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, SimpleRNN
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l1, l2
from tensorflow.keras.callbacks import EarlyStopping
from prophet import Prophet
import itertools
import seaborn as sns
import time
import re
import string
import chardet
import html
from collections import Counter
import plotly.express as px
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.probability import FreqDist
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import Ridge, LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
import scipy.sparse as sp
import datetime

#nomi azioni delle aziende interessate
aziende = ["AMZN", "WMT"]

for ticker in aziende:
    azienda = yf.Ticker(ticker)
    dati_storici = azienda.history(period="max")
    # Rendi l'indice (Date) timezone-unaware (senza fuso orario)
    if isinstance(dati_storici.index, pd.DatetimeIndex):
        dati_storici.index = dati_storici.index.tz_localize(None)
    # Salva i dati storici in un file Excel
    filename = f"{ticker}_dati_storici.xlsx"  # Crea un nome file univoco
    dati_storici.to_excel(filename)

"""# Amazon"""

df_a = pd.read_excel('AMZN_dati_storici.xlsx')
# Converti la colonna 'Date' in formato datetime
df_a['Date'] = pd.to_datetime(df_a['Date'])
print(df_a.head())

#attività su dividendi e stock_split
# Crea copie temporanee per dividendi e stock split
dividendi = df_a[df_a['Dividends'] != 0].copy()
stock_split = df_a[df_a['Stock Splits'] != 0].copy()

# Visualizza le date e i valori di dividendi e stock split
print("Date dei dividendi:")
print(dividendi[['Date', 'Dividends']])

print("\nDate degli stock split:")
print(stock_split[['Date', 'Stock Splits']])

# 1. Grafico dei volumi
plt.figure(figsize=(12, 6))
plt.plot(df_a['Date'], df_a['Volume'], label='Volume', color='blue')
plt.title('Volumi nel tempo')
plt.xlabel('Data')
plt.ylabel('Volume')
plt.grid(True)
plt.legend()
plt.show()

# 2. Grafico High e Low
plt.figure(figsize=(12, 6))
plt.plot(df_a['Date'], df_a['High'], label='High', color='green')
plt.plot(df_a['Date'], df_a['Low'], label='Low', color='red')
plt.title('High e Low nel tempo')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

# 3. Grafico Open e Close
plt.figure(figsize=(12, 6))
plt.plot(df_a['Date'], df_a['Open'], label='Open', color='purple')
plt.plot(df_a['Date'], df_a['Close'], label='Close', color='orange')
plt.title('Open e Close nel tempo')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

"""# trasformazione logaritmica
La trasformazione logaritmica consiste nell'applicare la funzione logaritmo a ciascun valore della serie temporale. Una serie temporale può avere una varianza che cambia nel tempo (eteroschedasticità). La trasformazione logaritmica può aiutare a stabilizzare la varianza, rendendo la serie più adatta per l'analisi. Se la serie temporale mostra una crescita esponenziale, la trasformazione logaritmica può linearizzare la relazione, facilitando la modellazione. In alcuni casi, la trasformazione logaritmica può rendere la distribuzione dei dati più simile a una distribuzione normale, che è un'assunzione per alcune tecniche statistiche.

"""

#trasformazione logaritmica
# Crea una copia di df_a
df_a_log = df_a.copy()

# Colonne numeriche da trasformare (escludi 'Date' e colonne non numeriche)
numeric_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

# Applica la trasformazione logaritmica alle colonne numeriche
for col in numeric_cols:
    # Aggiungi una piccola costante per evitare logaritmi di zero o valori negativi
    df_a_log[col] = np.log(df_a_log[col])
# Visualizza le prime righe di df_a_log
print(df_a_log.head())

# 1. Grafico dei volumi
plt.figure(figsize=(12, 6))
plt.plot(df_a_log['Date'], df_a_log['Volume'], label='Volume', color='blue')
plt.title('Volumi nel tempo log')
plt.xlabel('Data')
plt.ylabel('Volume')
plt.grid(True)
plt.legend()
plt.show()

# 2. Grafico High e Low
plt.figure(figsize=(12, 6))
plt.plot(df_a_log['Date'], df_a_log['High'], label='High', color='green')
plt.plot(df_a_log['Date'], df_a_log['Low'], label='Low', color='red')
plt.title('High e Low nel tempo log')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

# 3. Grafico Open e Close
plt.figure(figsize=(12, 6))
plt.plot(df_a_log['Date'], df_a_log['Open'], label='Open', color='purple')
plt.plot(df_a_log['Date'], df_a_log['Close'], label='Close', color='orange')
plt.title('Open e Close nel tempo log')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

# Calcola le variazioni percentuali sui dati originali
variations_a = df_a[['Open', 'High', 'Low', 'Close']].pct_change()

# Aggiungi la colonna 'Date' al DataFrame delle variazioni
variations_a['Date'] = df_a['Date']

# Visualizza le prime righe del DataFrame delle variazioni
print(variations_a.head())

# Plot delle variazioni
plt.figure(figsize=(12, 6))
plt.plot(variations_a['Date'], variations_a['Open'], label='Variazione Open', color='blue')
plt.plot(variations_a['Date'], variations_a['Close'], label='Variazione Close', color='orange')
plt.title('Variazioni percentuali nel tempo')
plt.xlabel('Data')
plt.ylabel('Variazione percentuale')
plt.grid(True)
plt.legend()
plt.show()

#dati originali
# Esegui il test ADF
lista= ["Open", "Close", "Volume"]
for i in lista:
    adf_test = adfuller(df_a[i])

    # Estrai i risultati
    statistic = adf_test[0]
    pvalue = adf_test[1]
    critical_values = adf_test[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

#dati log
# Esegui il test ADF
lista= ["Open", "Close", "Volume"]
for i in lista:
    adf_test_log = adfuller(df_a_log[i])

    # Estrai i risultati
    statistic = adf_test_log[0]
    pvalue = adf_test_log[1]
    critical_values = adf_test_log[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

"""# differenziazione:
è una tecnica che consiste nel calcolare la differenza tra valori consecutivi in una serie temporale. Molte tecniche di analisi delle serie temporali, come i modelli ARIMA, richiedono che la serie sia stazionaria. Una serie stazionaria ha proprietà statistiche (media, varianza) costanti nel tempo. La differenziazione è spesso utilizzata per rimuovere la tendenza e la stagionalità, che rendono le serie non stazionarie.
"""

# Applica la differenziazione
df_a_trasf = df_a_log.diff().dropna()
#ADF sui dati trasformati
for i in lista:
    adf_test_trasf = adfuller(df_a_trasf[i])

    # Estrai i risultati
    statistic = adf_test_trasf[0]
    pvalue = adf_test_trasf[1]
    critical_values = adf_test_trasf[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

# Crea una copia di df_a
df_a_decomp = df_a.copy()

# Imposta la colonna 'Date' come indice
df_a_decomp.set_index('Date', inplace=True)

for i in lista:
    data = df_a_decomp[i]

    # Applica la decomposizione stagionale
    decomposition = seasonal_decompose(data, model='additive', period=365)  # Modifica il periodo se necessario

    # Visualizza la decomposizione
    decomposition.plot()
    plt.show()

    # Estrai i residui
    resid = decomposition.resid.dropna()

    # Esegui il test ADF sui residui
    adf_test = adfuller(resid)

    # Estrai i risultati
    statistic = adf_test[0]
    pvalue = adf_test[1]
    critical_values = adf_test[4]

    # Stampa i risultati
    print("Statistica ADF sui residui:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

"""Se il test di stazionarietà (come il test ADF) restituisce stazionarietà per i residui, questo è un risultato positivo. Significa che i residui del tuo modello di decomposizione sono stazionari e si comportano come rumore bianco, il che è un'assunzione importante per molti modelli di serie temporali. Indica che il modello di decomposizione (additivo o moltiplicativo) è riuscito a separare correttamente le componenti di trend e stagionalità dalla serie temporale originale.

# Metodi di Previsione

## Metodi con dataset stazionario
"""

#preso i valori di close con operazione diff. e trasf. log. mentre i valori volume gli originali perhché già stazionari
data_a = pd.DataFrame({
    'Close': df_a_trasf['Close'],
    'Open': df_a_trasf['Open']
})
# Dividi i dati in train e test set
train_a, test_a = train_test_split(data_a, test_size=0.2, shuffle=False)

# Visualizza le dimensioni dei set
print("Dimensione train_a:", train_a.shape)
print("Dimensione test_a:", test_a.shape)

# Visualizza le prime righe dei set
print("\nTrain_a:")
print(train_a.head())
print(train_a.tail())

print("\nTest_a:")
print(test_a.head())
print(test_a.tail())

#verifica di valori 0 o infinito
print(data_a['Close'][data_a['Close'].isna()])
print(data_a['Close'][np.isinf(data_a['Close'])])
print(data_a['Open'][data_a['Open'].isna()])
print(data_a['Open'][np.isinf(data_a['Open'])])

# Gestisci il valore NaN (esempio: imputazione con la media)
data_a['Close'] = data_a['Close'].fillna(data_a['Close'].mean())

# Verifica la correzione
print(data_a['Close'].isna().sum())
print(data_a['Close'].isin([np.inf, -np.inf]).sum())
print(data_a['Open'].isna().sum())
print(data_a['Open'].isin([np.inf, -np.inf]).sum())

lista1= ['Close', 'Open']
for i in lista1:
    adf_test_data_a = adfuller(data_a[i])

    # Estrai i risultati
    statistic = adf_test_data_a[0]
    pvalue = adf_test_data_a[1]
    critical_values = adf_test_data_a[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

for campo in data_a:
    print (campo)
    plot_pacf(data_a[campo], lags=20)
    plt.show()
    plot_acf(data_a[campo], lags=20)
    plt.show()

def calcola_metriche(y_true, y_pred):
    # Rimuovi i valori NaN
    y_true = y_true.dropna()
    y_pred = y_pred.dropna()
    # Allinea gli indici per garantire che y_true e y_pred abbiano la stessa lunghezza
    y_true, y_pred = y_true.align(y_pred, join='inner')
    me = np.mean(y_pred - y_true)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    mpe = np.mean((y_true - y_pred) / y_true) * 100
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    return me, rmse, mae, mpe, mape

def modello_arima(train,test,p,d,q):
    modello_arima = ARIMA(train, order=(p, d, q))
    risultati_arima = modello_arima.fit()
    # Effettua le previsioni sul set di train
    previsioni_train_arima = risultati_arima.predict(start=0, end=len(train) - 1)
    # Effettua le previsioni sul set di test
    previsioni_test_arima = risultati_arima.predict(start=len(train), end=len(train) + len(test) - 1)
    me_train, rmse_train, mae_train, mpe_train, mape_train = calcola_metriche(train, previsioni_train_arima)
    print('Valutazione train')
    print(f"ME: {me_train}, RMSE: {rmse_train}, MAE: {mae_train}, MPE: {mpe_train}, MAPE: {mape_train}")
    me_test, rmse_test, mae_test, mpe_test, mape_test = calcola_metriche(test, previsioni_test_arima)
    print('Valutazione test')
    print(f"ME: {me_test}, RMSE: {rmse_test}, MAE: {mae_test}, MPE: {mpe_test}, MAPE: {mape_test}")
    # Visualizza le previsioni rispetto ai dati reali
    plt.figure(figsize=(12, 6))
    plt.plot(train, label='Train')
    plt.plot(test.index, test, label='Test')
    plt.plot(train.index, previsioni_train_arima, label='Previsioni Train', color='red')
    plt.plot(test.index, previsioni_test_arima, label='Previsioni Test', color='green')
    plt.legend()
    plt.title('Previsioni ARIMA')
    plt.show()
    return risultati_arima

modello_arima(train_a['Close'], test_a['Close'], 4, 0, 4)
modello_arima(train_a['Open'], test_a['Open'], 2, 0, 1)

#arima iterativo
def modello_arima_iterativo(train, test, p_range, d_range, q_range):
    miglior_rmse = float('inf')
    miglior_modello = None
    migliori_parametri = None
    pdq = list(itertools.product(p_range, d_range, q_range))

    print(pdq)

    for param in pdq:
        rmse_test = None
        try:
            modello_arima = ARIMA(train, order=param)
            risultati_arima = modello_arima.fit()
            previsioni_test_arima = risultati_arima.predict(start=len(train), end=len(train) + len(test) - 1)
            rmse_test = mean_squared_error(test, previsioni_test_arima, squared=False)

            if rmse_test < miglior_rmse:
                miglior_rmse = rmse_test
                miglior_modello = risultati_arima
                migliori_parametri = param

        except:
            pass

        print(f"Parametri: {param}, RMSE: {rmse_test}")

    print(f"Migliori parametri: {migliori_parametri}")
    print(f"Miglior RMSE: {miglior_rmse}")

    # Visualizza le previsioni del miglior modello (se trovato)
    if miglior_modello is not None:
        previsioni_train_arima = miglior_modello.predict(start=0, end=len(train) - 1)
        previsioni_test_arima = miglior_modello.predict(start=len(train), end=len(train) + len(test) - 1)
    else:
        previsioni_train_arima = np.zeros(len(train)) # Inizializza con zeri
        previsioni_test_arima = np.zeros(len(test)) # Inizializza con zeri

    plt.figure(figsize=(12, 6))
    plt.plot(train, label='Train')
    plt.plot(test.index, test, label='Test')
    plt.plot(train.index, previsioni_train_arima, label='Previsioni Train', color='red')
    plt.plot(test.index, previsioni_test_arima, label='Previsioni Test', color='green')
    plt.legend()
    plt.title('Previsioni ARIMA')
    plt.show()

    return miglior_modello

p_range = range(0, 4)
d_range = range(0, 3)
q_range = range(0, 4)

miglior_modello = modello_arima_iterativo(train_a['Close'], test_a['Close'], p_range, d_range, q_range)
miglior_modello = modello_arima_iterativo(train_a['Open'], test_a['Open'], p_range, d_range, q_range)

"""# analisi modello Close
Le metriche ME, RMSE e MAE sono relativamente basse, suggerendo una buona capacità del modello di adattarsi ai dati di train e test. Tuttavia, i valori infiniti di MPE e MAPE sollevano preoccupazioni. Confrontando le performance del train e del test, le metriche sono simili, il che suggerisce che il modello non sta andando in Overfitting. Ma i valori infiniti di MPE e MAPE invalidano questa affermazione. Potrebbero essere dovuti a valori zero nei dati trasformati o a problemi con la differenziazione.
# analisi modello Open

# Prophet
"""

#preparazione del dataset per prophet
data_a_prophet = pd.DataFrame({
    'ds': df_a['Date'],
    'Close': df_a_trasf['Close'],
    'Open': df_a_trasf['Open']
})
data_a_prophet['ds'] = pd.to_datetime(data_a_prophet['ds'])
# Gestisci il valore NaN (esempio: imputazione con la media)
data_a_prophet['Close'] = data_a_prophet['Close'].fillna(data_a['Close'].mean())
data_a_prophet['Open'] = data_a_prophet['Close'].fillna(data_a['Open'].mean())
# Dividi i dati in train e test set
train_a_prophet, test_a_prophet = train_test_split(data_a_prophet, test_size=0.2, shuffle=False)

train_a_prophet.head

#preparazione del train e test
# Preparazione dei dati per Prophet (Close)
train_close = train_a_prophet[['ds', 'Close']].rename(columns={'Close': 'y'})
test_close = test_a_prophet[['ds', 'Close']].rename(columns={'Close': 'y'})

# Preparazione dei dati per Prophet (Volume)
train_open = train_a_prophet[['ds', 'Open']].rename(columns={'Open': 'y'})
test_open = test_a_prophet[['ds', 'Open']].rename(columns={'Open': 'y'})

def modello_prophet(train,test):
    # Identifica e gestisci i valori nan nel train set
    train_nan_mask = train['y'].isna()
    train = train[~train_nan_mask]

    # Identifica e gestisci i valori nan nel test set
    test_nan_mask = test['y'].isna()
    test = test[~test_nan_mask]

    # Crea un modello Prophet
    model = Prophet(changepoint_prior_scale=0.01) # Valore più basso per ridurre l'overfitting

    # Addestra il modello sui dati di training
    model.fit(train)

    # Effettua le previsioni sul set di training
    forecast_train = model.predict(train)

    # Effettua le previsioni sul set di test
    forecast_test = model.predict(test)

    # Rimuovi i valori nan dalle previsioni e allinea gli indici
    forecast_test_nan_mask = forecast_test['yhat'].isna()
    forecast_test = forecast_test[~forecast_test_nan_mask].reset_index(drop=True) # Reset index
    test = test.reset_index(drop=True)[~forecast_test_nan_mask.reset_index(drop=True)] # reset and align index

    # Calcola le metriche di valutazione sul set di training
    me_train = np.mean(train['y'] - forecast_train['yhat'])
    rmse_train = np.sqrt(mean_squared_error(train['y'], forecast_train['yhat']))
    mae_train = np.mean(np.abs(train['y'] - forecast_train['yhat']))
    mpe_train = np.mean((train['y'] - forecast_train['yhat']) / train['y']) * 100
    mape_train = np.mean(np.abs((train['y'] - forecast_train['yhat']) / train['y'])) * 100

    # Calcola le metriche di valutazione sul set di test
    me_test = np.mean(test['y'] - forecast_test['yhat'])
    rmse_test = np.sqrt(mean_squared_error(test['y'], forecast_test['yhat']))
    mae_test = np.mean(np.abs(test['y'] - forecast_test['yhat']))
    mpe_test = np.mean((test['y'] - forecast_test['yhat']) / test['y']) * 100
    mape_test = np.mean(np.abs((test['y'] - forecast_test['yhat']) / test['y'])) * 100

    # Stampa le metriche di valutazione
    print('Valutazione train')
    print(f'ME: {me_train}, RMSE: {rmse_train}, MAE: {mae_train}, MPE: {mpe_train}, MAPE: {mape_train}')

    print('Valutazione test')
    print(f'ME: {me_test}, RMSE: {rmse_test}, MAE: {mae_test}, MPE: {mpe_test}, MAPE: {mape_test}')

    # Visualizza le previsioni rispetto ai valori reali
    plt.plot(train['ds'], train['y'], label='Train')
    plt.plot(test['ds'], test['y'], label='Test')
    plt.plot(forecast_test['ds'], forecast_test['yhat'], label='Predictions')
    plt.legend()
    plt.show()

    # Visualizza i componenti del modello
    model.plot_components(forecast_test)
    plt.show()

    return model

print ('Open')
# Applica il metodo a train_volume e test_volume
model_open = modello_prophet(train_open, test_open)

print ('Close')
# Applica il metodo a train_close e test_close
model_close = modello_prophet(train_close, test_close)

"""# Analisi Open

# Analisi Close
I valori di RMSE e MAE sono molto bassi sia per il set di training che per il set di test, il che suggerisce che il modello è in grado di prevedere i valori "Close" con una buona precisione.
Tuttavia, i valori di MPE e MAPE sono nan (Not a Number) e inf (infinito), rispettivamente. Questo indica che ci sono state divisioni per zero durante il calcolo di queste metriche, il che può accadere se i valori reali o le previsioni sono zero o molto vicini a zero.

# Metodi con dataset non stazionario
"""

# Preparazione del dataset usato dati log. per problemi di differenza di distribuzione dei dati tra train e test
close_data = df_a_log['Close'].values.reshape(-1, 1)
open_data = df_a_log['Open'].values.reshape(-1, 1)
#divisione train e test
train_a_rnn_close, test_a_rnn_close = train_test_split(close_data, test_size=0.2, shuffle=False)
train_a_rnn_open, test_a_rnn_open = train_test_split(open_data, test_size=0.2, shuffle=False)

print (train_a_rnn_close)

# Crea il istogrammi
# Appiattisci l'array in un array unidimensionale
train_a_rnn_close_flat = train_a_rnn_close.flatten()
df = pd.DataFrame({'valori': train_a_rnn_close_flat})

# Appiattisci l'array in un array unidimensionale
test_a_rnn_close_flat = test_a_rnn_close.flatten()
df_t = pd.DataFrame({'valori': test_a_rnn_close_flat,})


# Crea gli istogrammi
plt.figure(figsize=(12, 6))  # Imposta la dimensione della figura

plt.subplot(1, 2, 1)  # Crea il primo subplot (1 riga, 2 colonne, posizione 1)
sns.histplot(train_a_rnn_close_flat, bins=30, kde=True)
plt.title('Istogramma Close_train')
plt.xlabel('Valori')
plt.ylabel('Frequenza')

plt.subplot(1, 2, 2)  # Crea il secondo subplot (1 riga, 2 colonne, posizione 2)
sns.histplot(test_a_rnn_close_flat, bins=30, kde=True)
plt.title('Istogramma Close_test')
plt.xlabel('Valori')
plt.ylabel('Frequenza')

plt.tight_layout()  # Aggiusta la spaziatura tra i subplot
plt.show()

"""## RNN"""

def modello_rnn(train, test, seq_length=10, epochs=100, learning_rate=0.001, dropout_rate=0.3, l2_rate=0.01):
    # 1. Preparazione dei dati
    scaler = MinMaxScaler()
    scaled_train = scaler.fit_transform(train.reshape(-1, 1))
    scaled_test = scaler.transform(test.reshape(-1, 1))

    def create_sequences(data, seq_length):
        xs = []
        ys = []
        for i in range(len(data) - seq_length):
            x = data[i:i+seq_length]
            y = data[i+seq_length]
            xs.append(x)
            ys.append(y)
        return np.array(xs), np.array(ys)

    X_train, y_train = create_sequences(scaled_train, seq_length)
    X_test, y_test = create_sequences(scaled_test, seq_length)

    # 2. Costruzione e addestramento del modello RNN
    model = Sequential()
    model.add(SimpleRNN(50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2]), kernel_regularizer=l2(l2_rate)))  # Solo L2 a LSTM
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, kernel_regularizer=l2(l2_rate)))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse')
    # Aggiungi EarlyStopping
    early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)  # Configura EarlyStopping
    history = model.fit(X_train, y_train, epochs=epochs, validation_split=0.2, verbose=0)
    # 3. Effettua le previsioni
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # 4. Inverti la scala delle previsioni
    y_train_pred_original = scaler.inverse_transform(y_train_pred)
    y_test_pred_original = scaler.inverse_transform(y_test_pred)
    y_train_original = scaler.inverse_transform(y_train)
    y_test_original = scaler.inverse_transform(y_test)

    # 5. Calcola le metriche di valutazione
    rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred_original))
    mae_train = mean_absolute_error(y_train_original, y_train_pred_original)
    mpe_train = np.mean((y_train_original - y_train_pred_original) / y_train_original) * 100
    mape_train = np.mean(np.abs((y_train_original - y_train_pred_original) / y_train_original)) * 100

    rmse_test = np.sqrt(mean_squared_error(y_test_original, y_test_pred_original))
    mae_test = mean_absolute_error(y_test_original, y_test_pred_original)
    mpe_test = np.mean((y_test_original - y_test_pred_original) / y_test_original) * 100
    mape_test = np.mean(np.abs((y_test_original - y_test_pred_original) / y_test_original)) * 100

    # 6. Stampa le metriche di valutazione
    print("Valutazione train")
    print(f"ME: {np.mean(y_train_original - y_train_pred_original)}, RMSE: {rmse_train}, MAE: {mae_train}, MPE: {mpe_train}, MAPE: {mape_train}")
    print("Valutazione test")
    print(f"ME: {np.mean(y_test_original - y_test_pred_original)}, RMSE: {rmse_test}, MAE: {mae_test}, MPE: {mpe_test}, MAPE: {mape_test}")

    # 7. Visualizza le previsioni
    plt.figure(figsize=(12, 6))
    plt.plot(range(len(train)), train, label='Train')
    plt.plot(range(len(train), len(train) + len(test)), test, label='Test')
    plt.plot(range(len(train) + seq_length, len(train) + len(test)), y_test_pred_original, label='Predictions')
    plt.legend()
    plt.show()

    return model, history

# Esempio di utilizzo per la colonna "Close"
print ('CLose')
model_close, history_close = modello_rnn(train_a_rnn_close, test_a_rnn_close, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_close.history['loss'], label='Loss (train)')
plt.plot(history_close.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()

# Esempio di utilizzo per la colonna "Open"
print ('Open')
model_open, history_open = modello_rnn(train_a_rnn_open, test_a_rnn_open, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_open.history['loss'], label='Loss (train)')
plt.plot(history_open.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()

"""## LSTM"""

def modello_lstm(train, test, seq_length=10, epochs=100, learning_rate=0.001, dropout_rate=0.2, l2_rate=0.001):
    # 1. Preparazione dei dati
    scaler = MinMaxScaler()
    scaled_train = scaler.fit_transform(train.reshape(-1, 1))
    scaled_test = scaler.transform(test.reshape(-1, 1))

    def create_sequences(data, seq_length):
        xs = []
        ys = []
        for i in range(len(data) - seq_length):
            x = data[i:i+seq_length]
            y = data[i+seq_length]
            xs.append(x)
            ys.append(y)
        return np.array(xs), np.array(ys)

    X_train, y_train = create_sequences(scaled_train, seq_length)
    X_test, y_test = create_sequences(scaled_test, seq_length)

    # 2. Costruzione e addestramento del modello LSTM con Dropout e L2
    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2]), kernel_regularizer=l2(l2_rate)))  # Utilizza LSTM
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, kernel_regularizer=l2(l2_rate)))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse')

    # Aggiungi EarlyStopping
    early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

    history = model.fit(X_train, y_train, epochs=epochs, validation_split=0.2, verbose=0, callbacks=[early_stopping])

    # 3. Effettua le previsioni
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # 4. Inverti la scala delle previsioni
    y_train_pred_original = scaler.inverse_transform(y_train_pred)
    y_test_pred_original = scaler.inverse_transform(y_test_pred)
    y_train_original = scaler.inverse_transform(y_train)
    y_test_original = scaler.inverse_transform(y_test)

    # 5. Calcola le metriche di valutazione
    rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred_original))
    mae_train = mean_absolute_error(y_train_original, y_train_pred_original)
    mpe_train = np.mean((y_train_original - y_train_pred_original) / y_train_original) * 100
    mape_train = np.mean(np.abs((y_train_original - y_train_pred_original) / y_train_original)) * 100

    rmse_test = np.sqrt(mean_squared_error(y_test_original, y_test_pred_original))
    mae_test = mean_absolute_error(y_test_original, y_test_pred_original)
    mpe_test = np.mean((y_test_original - y_test_pred_original) / y_test_original) * 100
    mape_test = np.mean(np.abs((y_test_original - y_test_pred_original) / y_test_original)) * 100

    # 6. Stampa le metriche di valutazione
    print("Valutazione train")
    print(f"ME: {np.mean(y_train_original - y_train_pred_original)}, RMSE: {rmse_train}, MAE: {mae_train}, MPE: {mpe_train}, MAPE: {mape_train}")
    print("Valutazione test")
    print(f"ME: {np.mean(y_test_original - y_test_pred_original)}, RMSE: {rmse_test}, MAE: {mae_test}, MPE: {mpe_test}, MAPE: {mape_test}")

    # 7. Visualizza le previsioni
    plt.figure(figsize=(12, 6))
    plt.plot(range(len(train)), train, label='Train')
    plt.plot(range(len(train), len(train) + len(test)), test, label='Test')
    plt.plot(range(len(train) + seq_length, len(train) + len(test)), y_test_pred_original, label='Predictions')
    plt.legend()
    plt.show()

    return model, history

# Esempio di utilizzo per la colonna "Close"
print ('CLose')
model_close, history_close = modello_lstm(train_a_rnn_close, test_a_rnn_close, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_close.history['loss'], label='Loss (train)')
plt.plot(history_close.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()

# Esempio di utilizzo per la colonna "Open"
print ('Open')
model_open, history_open = modello_lstm(train_a_rnn_open, test_a_rnn_open, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_open.history['loss'], label='Loss (train)')
plt.plot(history_open.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()

"""# Sentiment analysis"""

#per risolvere problemi di codifica del file
with open("/content/amazon_reviews_99-2012.csv", "rb") as f:  # Apri il file in modalità binaria ("rb")
    result = chardet.detect(f.read())

encoding = result['encoding']
print(f"Codifica rilevata: {encoding}")

# Caricamento dati
reviews_a = pd.read_csv("/amazon_reviews_99-2012.csv", encoding="MacRoman")

# Converti i timestamp in oggetti datetime
reviews_a['Time'] = pd.to_datetime(reviews_a['Time'], unit='s')

reviews_a.head

reviews_a.shape

print (reviews_a.columns)

# Istogramma per la colonna 'rating'
plt.figure(figsize=(8, 6))
sns.histplot(reviews_a['Score'], bins=10)
plt.title('Distribuzione dei Score')
plt.xlabel('Score')
plt.ylabel('Frequenza')
plt.show()

plt.figure(figsize=(8, 6))
sns.histplot(reviews_a['Time'], bins=10)  # kde=True aggiunge la stima della densità di kernel
plt.title('Distribuzione delle Date')
plt.xlabel('Date')
plt.ylabel('Frequenza')
plt.show()

# Informazioni generali sul dataset
print("\nInformazioni sul dataset:")
print(reviews_a.info())

nltk.download('punkt_tab')
nltk.download('stopwords')

# Dizionario di slang e acronimi (aggiungere altri se necessario)
slang_dict = {
    "u": "you", "ur": "your", "r": "are", "idk": "I don't know", "btw": "by the way",
    "imo": "in my opinion", "imho": "in my humble opinion", "lol": "laughing out loud",
    "lmao": "laughing my ass off", "brb": "be right back", "gtg": "got to go",
    "smh": "shaking my head", "omg": "oh my god", "thx": "thanks", "ty": "thank you",
    "pls": "please", "plz": "please", "gr8": "great", "b4": "before", "cuz": "because",
    "bc": "because", "wanna": "want to", "gonna": "going to", "gotta": "got to"
}
def clean_text(text):
    # Convertire in minuscolo
    text = text.lower()
    # Decodifica entità HTML (&quot; -> ", &amp; -> &, ecc.)
    text = html.unescape(text)
    # Rimuovere menzioni, URL e hashtag
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)  # Menzioni
    text = re.sub(r'https?://\S+', '', text)   # URL
    text = re.sub(r'#', '', text)               # Rimuove hashtag mantenendo la parola
    text = re.sub(r'www\.\S+', '', text)    # Rimuove URL che iniziano con www

    # Sostituzione di acronimi e slang
    words = text.split()
    words = [slang_dict[word] if word in slang_dict else word for word in words]
    text = ' '.join(words)

    # Rimozione di punteggiatura e numeri
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    # Tokenizzazione
    tokens = word_tokenize(text)

    # Rimozione stopwords
    stop_words = set(stopwords.words('english'))

    tokens = [word for word in tokens if word not in stop_words]

    # Rimozione della parola "walmart"
    words_to_remove = ["br", "walmart"]
    tokens = [word for word in tokens if word not in words_to_remove]

    # Stemming
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]

    return ' '.join(tokens)

# Applicare la pulizia alla colonna "SentimentText"
reviews_a["Text"] = reviews_a["Text"].astype(str).apply(clean_text)
reviews_a["Text"].head

#nuvola di parole
text = " ".join(reviews_a['Text'])
wordcloud = WordCloud(width=800, height=400, max_words=100, background_color='white', colormap='viridis').generate(text)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

# Filtra i revies
positive_texts = " ".join(reviews_a[reviews_a['Score'] == 1]['Text'])+' '.join(reviews_a[reviews_a['Score'] == 2]['Text'])
neutral_texts= " ".join(reviews_a[reviews_a['Score'] == 3]['Text'])
negative_texts = " ".join(reviews_a[reviews_a['Score'] == 4]['Text'])+' '.join(reviews_a[reviews_a['Score'] == 5]['Text'])


# Conta le parole più comuni per i testi positivi
top_pos = Counter(positive_texts.split())
top_pos_df = pd.DataFrame(top_pos.most_common(100), columns=['Words', 'Counts'])

# Conta le parole più comuni per i testi positivi
top_neu = Counter(neutral_texts.split())
top_neu_df = pd.DataFrame(top_neu.most_common(100), columns=['Words', 'Counts'])


# Conta le parole più comuni per i testi negativi
top_neg = Counter(negative_texts.split())
top_neg_df = pd.DataFrame(top_neg.most_common(100), columns=['Words', 'Counts'])

# Stampa i risultati
print("Parole più comuni nei testi positivi:")
print(top_pos_df.head())

print("Parole più comuni nei testi neutrali:")
print(top_neu_df.head())

print("\nParole più comuni nei testi negativi:")
print(top_neg_df.head())

fig,ax=plt.subplots(nrows=1,ncols=3,figsize=(15,7.5))
sns.barplot(y='Words',x='Counts',data=top_pos_df[:20],color='deepskyblue',ax=ax[0])
sns.barplot(y='Words',x='Counts',data=top_neu_df[:20],color='green',ax=ax[1])
sns.barplot(y='Words',x='Counts',data=top_neg_df[:20],color='coral',ax=ax[2])
ax[0].set_title("Most Frequent words in Positive review")
ax[1].set_title("Most Frequent words in Neutral review")
ax[2].set_title("Most Frequent words in Negative review")
plt.show()

#criteri empirici
def analisi_ttr_hapax(testo):
    tokens = word_tokenize(testo)
    tipi = set(tokens)
    ttr = len(tipi) / len(tokens) *100

    freq_dist = FreqDist(tokens)
    hapax = [word for word, freq in freq_dist.items() if freq == 1]
    percentuale_hapax = (len(hapax) / len(tokens)) * 100 if tokens else 0

    return ttr, percentuale_hapax

# Concatena tutte le recensioni in un'unica stringa
corpus_a = " ".join(reviews_a["Text"].tolist())

# Applica la funzione analisi_ttr_hapax all'intero corpus
ttr, percentuale_hapax = analisi_ttr_hapax(corpus_a)

# Stampa i risultati
print("TTR:", ttr)
print("Percentuale di Hapax:", percentuale_hapax)

#TF
# Crea un oggetto CountVectorizer
vectorizer = CountVectorizer()

# Adatta il vectorizer al corpus e trasforma il corpus in una matrice TFM
tf_matrix_a = vectorizer.fit_transform([corpus_a])

# Ottieni i nomi delle feature (i termini)
feature_names = vectorizer.get_feature_names_out()

# Crea un DataFrame pandas dalla matrice TFM
tf_df_a = pd.DataFrame(tf_matrix_a.toarray(), columns=feature_names)

# Visualizzazione delle Frequenze dei Termini

# Calcola la somma delle frequenze per ogni termine
term_frequencies_a = tf_df_a.sum()

# a. Boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(x=term_frequencies_a)
plt.title("Distribuzione delle Frequenze dei Termini nel Corpus")
plt.xlabel("Frequenza")
plt.show()

# Bilanciamento delle classi
# Calcola il numero di campioni per ogni classe
class_counts = reviews_a['Score'].value_counts()
print("Conteggio campioni per classe originale:\n", class_counts)
# Identifica la classe con il minor numero di campioni
min_count = class_counts.min()
print("\nNumero minimo di campioni per classe:", min_count)

# Separa il DataFrame per la classe 5 e le altre classi
df_classe_5 = reviews_a[reviews_a['Score'] == 5]
df_classe_4 = reviews_a[reviews_a['Score'] == 4]
df_classe_3 = reviews_a[reviews_a['Score'] == 3]
df_classe_2 = reviews_a[reviews_a['Score'] == 2]
df_classe_1 = reviews_a[reviews_a['Score'] == 1]

# Sottocampiona casualmente le classi al numero di campioni della classe meno rappresentata
df_classe_5_undersampled = df_classe_5.sample(n=min_count, random_state=42) # random_state per la riproducibilità
df_classe_4_undersampled = df_classe_4.sample(n=min_count, random_state=42) # random_state per la riproducibilità
df_classe_3_undersampled = df_classe_3.sample(n=min_count, random_state=42) # random_state per la riproducibilità
df_classe_2_undersampled = df_classe_2.sample(n=min_count, random_state=42) # random_state per la riproducibilità
df_classe_1_undersampled = df_classe_1.sample(n=min_count, random_state=42) # random_state per la riproducibilità

# Combina il DataFrame sottocampionato della classe 5 con le altre classi
reviews_a_balanced = pd.concat([df_classe_1_undersampled, df_classe_2_undersampled, df_classe_3_undersampled, df_classe_4_undersampled, df_classe_5_undersampled])

# Istogramma per la colonna 'Score'
plt.figure(figsize=(8, 6))
sns.histplot(reviews_a_balanced['Score'], bins=10)
plt.title('Distribuzione dei Score')
plt.xlabel('Score')
plt.ylabel('Frequenza')
plt.show()

reviews_a_balanced.head

#TF-IDF
# Crea un oggetto TfidfVectorizer
vectorizer_tfidf_a = TfidfVectorizer(max_df=1.0, min_df=1, stop_words='english')

# Adatta il vectorizer al corpus e trasforma il corpus in una matrice TDM
tfidf_matrix = vectorizer_tfidf_a.fit_transform(reviews_a_balanced["Text"])

from transformers import BertTokenizer, TFBertModel
import tensorflow as tf

model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
bert_model = TFBertModel.from_pretrained(model_name)

# Verifica se una GPU è disponibile per TensorFlow
if tf.config.list_physical_devices('GPU'):
    device = '/GPU:0'
    print("GPU disponibile, utilizzo:", device)
else:
    device = '/CPU:0'
    print("Nessuna GPU disponibile, utilizzo CPU:", device)

# La modalità di valutazione in TensorFlow si gestisce in modo diverso,
# spesso tramite tf.function o semplicemente evitando l'addestramento.

# Funzione per ottenere l'embedding BERT di un testo (adattata per TensorFlow)
def get_bert_embedding(text, tokenizer, model, max_length=128):
    encoded_input = tokenizer(text, padding=True, truncation=True, max_length=max_length, return_tensors='tf')
    with tf.device(device):
        outputs = model(**encoded_input)
        # Embedding dell'intera sequenza (del token [CLS])
        embedding = outputs.pooler_output.numpy()
        # Alternativa: media degli embedding di tutti i token
        # embedding = tf.reduce_mean(outputs.last_hidden_state, axis=1).numpy()
    return embedding.flatten()

embedding_dim = bert_model.config.hidden_size

# Identificazione della colonna di testo
if 'Review' in reviews_a_balanced.columns:
    text_column = 'Review'
elif 'Summary' in reviews_a_balanced.columns:
    text_column = 'Summary'
else:
    print("Nessuna colonna 'Review' o 'Summary' trovata. Assicurati che il DataFrame contenga il testo.")
    exit()

print(f"Generazione embedding BERT per la colonna: '{text_column}'")

# Creazione di una lista per contenere tutti gli embedding
all_embeddings = []

# Iterazione attraverso le recensioni e generazione degli embedding
for index, row in reviews_a_balanced.iterrows():
    text = str(row[text_column]) # Assicurati che il testo sia una stringa
    embedding = get_bert_embedding(text, tokenizer, bert_model)
    all_embeddings.append(embedding)

# Conversione della lista di embedding in un array numpy
embeddings_array = np.array(all_embeddings)

# Creazione di nuove colonne nel DataFrame per gli embedding
for i in range(embedding_dim):
    reviews_a_balanced[f'bert_embedding_{i}'] = embeddings_array[:, i]

print(f"Embedding BERT generati e aggiunti come {embedding_dim} nuove colonne al DataFrame 'reviews_a'.")
print(reviews_a_balanced.head())

from transformers import BertTokenizer, TFBertModel
import tensorflow as tf

model_name = 'distilbert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
bert_model = TFBertModel.from_pretrained(model_name)

# Verifica se una GPU è disponibile per TensorFlow
if tf.config.list_physical_devices('GPU'):
    device = '/GPU:0'
    print("GPU disponibile, utilizzo:", device)
else:
    device = '/CPU:0'
    print("Nessuna GPU disponibile, utilizzo CPU:", device)

# La modalità di valutazione in TensorFlow si gestisce in modo diverso,
# spesso tramite tf.function o semplicemente evitando l'addestramento.

# Funzione per ottenere l'embedding BERT di un testo (adattata per TensorFlow)
def get_bert_embedding(text, tokenizer, model, max_length=128):
    encoded_input = tokenizer(text, padding=True, truncation=True, max_length=max_length, return_tensors='tf')
    with tf.device(device):
        outputs = model(**encoded_input)
        # Embedding dell'intera sequenza (del token [CLS])
        embedding = outputs.pooler_output.numpy()
        # Alternativa: media degli embedding di tutti i token
        # embedding = tf.reduce_mean(outputs.last_hidden_state, axis=1).numpy()
    return embedding.flatten()

embedding_dim = bert_model.config.hidden_size

# Identificazione della colonna di testo
if 'Review' in reviews_a_balanced.columns:
    text_column = 'Review'
elif 'Summary' in reviews_a_balanced.columns:
    text_column = 'Summary'
else:
    print("Nessuna colonna 'Review' o 'Summary' trovata. Assicurati che il DataFrame contenga il testo.")
    exit()

print(f"Generazione embedding BERT per la colonna: '{text_column}'")

# Creazione di una lista per contenere tutti gli embedding
all_embeddings = []

# Iterazione attraverso le recensioni e generazione degli embedding
for index, row in reviews_a_balanced.iterrows():
    text = str(row[text_column]) # Assicurati che il testo sia una stringa
    embedding = get_bert_embedding(text, tokenizer, bert_model)
    all_embeddings.append(embedding)

# Conversione della lista di embedding in un array numpy
embeddings_array = np.array(all_embeddings)

# Creazione di nuove colonne nel DataFrame per gli embedding
for i in range(embedding_dim):
    reviews_a_balanced[f'bert_embedding_{i}'] = embeddings_array[:, i]

print(f"Embedding BERT generati e aggiunti come {embedding_dim} nuove colonne al DataFrame 'reviews_a'.")
print(reviews_a_balanced.head())

#LSA manca da inserire _balanced per dataset bilanciato
# Numero di componenti desiderate (argomenti latenti)
n_components = 4  # Puoi regolare questo valore

# Crea un oggetto TruncatedSVD
lsa_a = TruncatedSVD(n_components=n_components)

# Applica LSA alla matrice TF-IDF
lsa_matrix_a = lsa_a.fit_transform(tfidf_matrix)

# Ottieni i termini (feature names)
terms_a = vectorizer_tfidf_a.get_feature_names_out()

# Stampa i termini più importanti per ogni argomento latente
#for i, component in enumerate(lsa_a.components_):
#    terms_zipped = zip(terms_a, component)
#    top_terms = sorted(terms_zipped, key=lambda x: x[1], reverse=True)[:10]  # Ottieni i primi 10 termini
#    print(f"Argomento {i + 1}:")
#    for term, score in top_terms:
#        print(f"  {term}: {score:.4f}")

# Visualizzazione delle Parole per Topic con Grafico a Dispersione (Termini Limitati)
num_terms_to_display = 20  # Puoi regolare questo valore

for i, component in enumerate(lsa_a.components_):
    terms_zipped = zip(terms_a, component)
    top_terms = sorted(terms_zipped, key=lambda x: x[1], reverse=True)[:num_terms_to_display]
    terms, scores = zip(*top_terms)

    plt.figure(figsize=(10, 6))
    plt.scatter(scores, range(len(terms)))
    for j, term in enumerate(terms):
        plt.annotate(term, (scores[j], j))

    plt.title(f"Argomento {i + 1} - Grafico a Dispersione")
    plt.xlabel("Punteggio")
    plt.ylabel("Termini")
    plt.yticks([])  # Rimuovi i tick sull'asse y
    plt.show()

"""Argomento 1:
I termini con i punteggi più alti sono "coffe", "tast", "like", "tea", "flavor". Questi termini suggeriscono che l'argomento 1 è incentrato sul gusto e sull'esperienza del caffè e del tè.
Altri termini rilevanti includono "good", "love", "great", "product".
Argomento 2:
I termini con i punteggi più alti sono "coffe", "cup", "tea", "strong", "flavor". Anche in questo caso, il caffè e il tè sono centrali, ma con un'enfasi sul gusto forte e sulla preparazione.
Altri termini rilevanti includono "drink", "brew", "bold", "bitter".
Argomento 3:
Il termine "tea" domina questo argomento con un punteggio molto più alto rispetto agli altri termini.
Altri termini rilevanti includono "green", "drink", "ice", "bag". Questo suggerisce che l'argomento 3 è incentrato sul tè, in particolare sul tè verde e sulle bevande fredde.
Argomento 4: termine predominante "dog" con ulteriori termini relativi alle caratteristiche dei prodotti per animali domestici.
"""

#LDA
# Crea un oggetto CountVectorizer
vectorizer_lda_a = CountVectorizer(max_df=1.0, min_df=1, stop_words='english')

# Adatta il vectorizer al corpus e trasforma il corpus in una matrice DTM
dtm_a = vectorizer_lda_a.fit_transform(reviews_a_balanced["Text"])

# Numero di argomenti desiderati
n_topics = 3  # Puoi regolare questo valore

# Modifica i parametri alpha e beta
alpha = 0.1  # Puoi regolare questo valore
beta = 0.1  # Puoi regolare questo valore

# Crea un oggetto LatentDirichletAllocation con i parametri modificati
lda_a = LatentDirichletAllocation(n_components=n_topics, random_state=42, doc_topic_prior=alpha, topic_word_prior=beta)

# Applica LDA alla matrice DTM
lda_a.fit(dtm_a)

# Ottieni i termini (feature names)
terms_lda_a = vectorizer_lda_a.get_feature_names_out()

# Stampa i termini più importanti per ogni argomento
for i, topic in enumerate(lda_a.components_):
    terms_zipped = zip(terms_lda_a, topic)
    top_terms = sorted(terms_zipped, key=lambda x: x[1], reverse=True)[:10]  # Ottieni i primi 10 termini
    print(f"Argomento {i + 1}:")
    for term, score in top_terms:
        print(f"  {term}: {score:.4f}")

    # Visualizzazione con Grafico a Barre
    terms, scores = zip(*top_terms)
    plt.figure(figsize=(8, 6))
    sns.barplot(x=list(scores), y=list(terms))
    plt.title(f"Argomento {i + 1}")
    plt.xlabel("Punteggio")
    plt.ylabel("Termini")
    plt.show()

"""Osservazioni Generali:
Distribuzione dei Punteggi: La distribuzione dei punteggi è più equilibrata rispetto a prima. Ogni argomento ha alcuni termini dominanti con punteggi elevati e una coda di termini con punteggi più bassi, ma la differenza tra i punteggi è meno estrema.
Separazione degli Argomenti: Gli argomenti sembrano essere più distinti e coerenti. I termini in ogni argomento sono più strettamente correlati tra loro, suggerendo che LDA è stato in grado di identificare temi più specifici.
Argomenti:
Argomento 1: Recensioni che esprimono preferenze e valutazioni positive sul gusto e sull'esperienza con i prodotti.
Argomento 2: Recensioni che si concentrano sull'esperienza positiva con il caffè e sul suo gusto.
Argomento 3: Recensioni che esprimono valutazioni positive sui prodotti in generale.

# Apprendimento sui specifici topic
"""

# 1. Identificazione dei Topic e Assegnazione delle Recensioni
topic_probabilities = lda_a.transform(dtm_a)
reviews_a_balanced['topic'] = topic_probabilities.argmax(axis=1)

# 2. Creazione del Dataset Etichettato
data_lda_a = reviews_a_balanced[['Text', 'topic', 'Score']]

# 3. Preparazione dei Dati per la Classificazione
X_train, X_test, y_train, y_test = train_test_split(
    data_lda_a[['Text', 'topic']], data_lda_a['Score'], test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer()
X_train_text = vectorizer.fit_transform(X_train['Text'])
X_test_text = vectorizer.transform(X_test['Text'])

X_train_topic = pd.get_dummies(X_train['topic'], prefix='topic').values
X_test_topic = pd.get_dummies(X_test['topic'], prefix='topic').values
# Questa riga di codice converte la colonna 'topic' in un array di variabili dummy
# Combina le caratteristiche manualmente
X_train_combined = sp.hstack((X_train_text, X_train_topic))
X_test_combined = sp.hstack((X_test_text, X_test_topic))
#Questa funzione di scipy.sparse è progettata per concatenare matrici sparse e array densi in modo efficiente.

print(y_train)

print (X_train_text)
print (X_train_topic)
print (X_train_combined)

print (X_train)
print (X_test)

"""### Modello Logistic Regression"""

def model_logistic_regression(X_train, X_test, y_train, y_test):
    # 1. Creazione e addestramento del modello
    model_lg = LogisticRegression(max_iter=500, random_state=42)
    model_lg.fit(X_train, y_train)

    # 2. Previsioni sul test set
    y_pred_test = model_lg.predict(X_test)
    y_pred_train = model_lg.predict(X_train)

# 3. Calcola le metriche di valutazione per la classificazione
    accuracy_train = accuracy_score(y_train, y_pred_train)
    precision_train = precision_score(y_train, y_pred_train, average='weighted')
    recall_train = recall_score(y_train, y_pred_train, average='weighted')
    f1_train = f1_score(y_train, y_pred_train, average='weighted')

    accuracy_test = accuracy_score(y_test, y_pred_test)
    precision_test = precision_score(y_test, y_pred_test, average='weighted')
    recall_test = recall_score(y_test, y_pred_test, average='weighted')
    f1_test = f1_score(y_test, y_pred_test, average='weighted')

    # 4. Stampa le metriche di valutazione
    print("Valutazione train")
    print(f"Accuracy: {accuracy_train}, Precision: {precision_train}, Recall: {recall_train}, F1-score: {f1_train}")
    print("Valutazione test")
    print(f"Accuracy: {accuracy_test}, Precision: {precision_test}, Recall: {recall_test}, F1-score: {f1_test}")

    return model_lg

modello_log_reg= model_logistic_regression(X_train_combined,X_test_combined, y_train, y_test)

"""### Gradient Boosting"""

def model_gradient_boosting(X_train, X_test, y_train, y_test):
     # 1. Creazione e addestramento del modello
    model_gb = GradientBoostingClassifier(n_estimators=100, max_depth=3, learning_rate=0.5, subsample=0.75)
    model_gb.fit(X_train, y_train)

    # 2. Previsioni sul test set
    y_pred_test = model_gb.predict(X_test)
    y_pred_train = model_gb.predict(X_train)

# 3. Calcola le metriche di valutazione per la classificazione
    accuracy_train = accuracy_score(y_train, y_pred_train)
    precision_train = precision_score(y_train, y_pred_train, average='weighted')
    recall_train = recall_score(y_train, y_pred_train, average='weighted')
    f1_train = f1_score(y_train, y_pred_train, average='weighted')

    accuracy_test = accuracy_score(y_test, y_pred_test)
    precision_test = precision_score(y_test, y_pred_test, average='weighted')
    recall_test = recall_score(y_test, y_pred_test, average='weighted')
    f1_test = f1_score(y_test, y_pred_test, average='weighted')

    # 4. Stampa le metriche di valutazione
    print("Valutazione train")
    print(f"Accuracy: {accuracy_train}, Precision: {precision_train}, Recall: {recall_train}, F1-score: {f1_train}")
    print("Valutazione test")
    print(f"Accuracy: {accuracy_test}, Precision: {precision_test}, Recall: {recall_test}, F1-score: {f1_test}")

    return model_gb

modello_gb= model_gradient_boosting(X_train_combined,X_test_combined, y_train, y_test)

"""### Random Forest

"""

def model_random_forest(X_train, X_test, y_train, y_test):

    # Avvio del timer
    start_time = time.time()

    # Creazione del modello Random Forest con parametri standard
    model_rf = RandomForestClassifier(n_estimators=100,
                                        max_depth=3,
                                        min_samples_split=5,
                                        random_state=42,
                                        n_jobs=-1)

    # Addestriamo il modello con i dati di training
    model_rf.fit(X_train, y_train)

    # Previsioni sul test set
    y_pred_test = model_rf.predict(X_test)
    y_pred_train = model_rf.predict(X_train)

# 3. Calcola le metriche di valutazione per la classificazione
    accuracy_train = accuracy_score(y_train, y_pred_train)
    precision_train = precision_score(y_train, y_pred_train, average='weighted')
    recall_train = recall_score(y_train, y_pred_train, average='weighted')
    f1_train = f1_score(y_train, y_pred_train, average='weighted')

    accuracy_test = accuracy_score(y_test, y_pred_test)
    precision_test = precision_score(y_test, y_pred_test, average='weighted')
    recall_test = recall_score(y_test, y_pred_test, average='weighted')
    f1_test = f1_score(y_test, y_pred_test, average='weighted')

    # 4. Stampa le metriche di valutazione
    print("Valutazione train")
    print(f"Accuracy: {accuracy_train}, Precision: {precision_train}, Recall: {recall_train}, F1-score: {f1_train}")
    print("Valutazione test")
    print(f"Accuracy: {accuracy_test}, Precision: {precision_test}, Recall: {recall_test}, F1-score: {f1_test}")

    # Calcolo del tempo di esecuzione
    end_time = time.time()
    execution_time = end_time - start_time
    print(f"\n⏳ Tempo di esecuzione: {execution_time:.2f} secondi")

    return model_rf, execution_time

modello_rf= model_random_forest(X_train_combined,X_test_combined, y_train, y_test)

"""# Walmart"""

df_w = pd.read_excel('WMT_dati_storici.xlsx')
# Converti la colonna 'Date' in formato datetime
df_w['Date'] = pd.to_datetime(df_w['Date'])
print(df_w.head())

# Crea copie temporanee per dividendi e stock split
dividendi_w = df_w[df_w['Dividends'] != 0].copy()
stock_split_w = df_w[df_w['Stock Splits'] != 0].copy()

# Visualizza le date e i valori di dividendi e stock split
print("Date dei dividendi:")
print(dividendi_w[['Date', 'Dividends']])

print("\nDate degli stock split:")
print(stock_split_w[['Date', 'Stock Splits']])

# Grafico a linee dei dividendi
plt.figure(figsize=(12, 6))
plt.plot(dividendi_w['Date'], dividendi_w['Dividends'], marker='o', linestyle='-')
plt.title('Dividendi nel tempo')
plt.xlabel('Data')
plt.ylabel('Dividendi')
plt.grid(True)
plt.show()

# 1. Grafico dei volumi
plt.figure(figsize=(12, 6))
plt.plot(df_w['Date'], df_w['Volume'], label='Volume', color='blue')
plt.title('Volumi nel tempo')
plt.xlabel('Data')
plt.ylabel('Volume')
plt.grid(True)
plt.legend()
plt.show()

# 2. Grafico High e Low
plt.figure(figsize=(12, 6))
plt.plot(df_w['Date'], df_w['High'], label='High', color='green')
plt.plot(df_w['Date'], df_w['Low'], label='Low', color='red')
plt.title('High e Low nel tempo')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

# 3. Grafico Open e Close
plt.figure(figsize=(12, 6))
plt.plot(df_w['Date'], df_w['Open'], label='Open', color='purple')
plt.plot(df_w['Date'], df_w['Close'], label='Close', color='orange')
plt.title('Open e Close nel tempo')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

#trasformazione logaritmica
# Crea una copia di df_w
df_w_log = df_w.copy()

# Colonne numeriche da trasformare (escludi 'Date' e colonne non numeriche)
numeric_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

# Applica la trasformazione logaritmica alle colonne numeriche
for col in numeric_cols:
    # Aggiungi una piccola costante per evitare logaritmi di zero o valori negativi
    df_w_log[col] = np.log(df_w_log[col])
# Visualizza le prime righe di df_w_log
print(df_w_log.head())

# 1. Grafico dei volumi
plt.figure(figsize=(12, 6))
plt.plot(df_w_log['Date'], df_w_log['Volume'], label='Volume', color='blue')
plt.title('Volumi nel tempo log')
plt.xlabel('Data')
plt.ylabel('Volume')
plt.grid(True)
plt.legend()
plt.show()

# 2. Grafico High e Low
plt.figure(figsize=(12, 6))
plt.plot(df_w_log['Date'], df_w_log['High'], label='High', color='green')
plt.plot(df_w_log['Date'], df_w_log['Low'], label='Low', color='red')
plt.title('High e Low nel tempo log')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

# 3. Grafico Open e Close
plt.figure(figsize=(12, 6))
plt.plot(df_w_log['Date'], df_w_log['Open'], label='Open', color='purple')
plt.plot(df_w_log['Date'], df_w_log['Close'], label='Close', color='orange')
plt.title('Open e Close nel tempo log')
plt.xlabel('Data')
plt.ylabel('Prezzo')
plt.grid(True)
plt.legend()
plt.show()

# Calcola le variazioni percentuali sui dati originali
variations_w = df_a[['Open', 'High', 'Low', 'Close']].pct_change()

# Aggiungi la colonna 'Date' al DataFrame delle variazioni
variations_w['Date'] = df_a['Date']

# Visualizza le prime righe del DataFrame delle variazioni
print(variations_w.head())

# Plot delle variazioni
plt.figure(figsize=(12, 6))
plt.plot(variations_w['Date'], variations_w['Open'], label='Variazione Open', color='blue')
plt.plot(variations_w['Date'], variations_w['Close'], label='Variazione Close', color='orange')
plt.title('Variazioni percentuali nel tempo')
plt.xlabel('Data')
plt.ylabel('Variazione percentuale')
plt.grid(True)
plt.legend()
plt.show()

#dati originali
# Esegui il test ADF
lista= ["Open", "Close", "Volume"]
for i in lista:
    adf_test = adfuller(df_w[i])

    # Estrai i risultati
    statistic = adf_test[0]
    pvalue = adf_test[1]
    critical_values = adf_test[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

# dati log
# Esegui il test ADF
lista= ["Open", "Close", "Volume"]
for i in lista:
    adf_test_log = adfuller(df_w_log[i])

    # Estrai i risultati
    statistic = adf_test_log[0]
    pvalue = adf_test_log[1]
    critical_values = adf_test_log[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

# Applica la differenziazione
df_w_trasf = df_w_log.diff().dropna()
#ADF sui dati trasformati
for i in lista:
    adf_test_trasf = adfuller(df_w_trasf[i])

    # Estrai i risultati
    statistic = adf_test_trasf[0]
    pvalue = adf_test_trasf[1]
    critical_values = adf_test_trasf[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

# Crea una copia di df_a
df_w_decomp = df_w.copy()

# Imposta la colonna 'Date' come indice
df_w_decomp.set_index('Date', inplace=True)

for i in lista:
    data = df_w_decomp[i]

    # Applica la decomposizione stagionale
    decomposition = seasonal_decompose(data, model='additive', period=365)  # Modifica il periodo se necessario

    # Visualizza la decomposizione
    decomposition.plot()
    plt.show()

    # Estrai i residui
    resid = decomposition.resid.dropna()

    # Esegui il test ADF sui residui
    adf_test = adfuller(resid)

    # Estrai i risultati
    statistic = adf_test[0]
    pvalue = adf_test[1]
    critical_values = adf_test[4]

    # Stampa i risultati
    print("Statistica ADF sui residui:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

"""# Metodi di Previsione

## Metodi con dataset stazionario
"""

#preso i valori di close con operazione diff. e trasf. log. mentre i valori volume gli originali perhché già stazionari
data_w = pd.DataFrame({
    'Close': df_w_trasf['Close'],
    'Open': df_w_trasf['Open']
})
# Dividi i dati in train e test set
train_w, test_w = train_test_split(data_w, test_size=0.2, shuffle=False)

# Visualizza le dimensioni dei set
print("Dimensione train_w:", train_w.shape)
print("Dimensione test_w:", test_w.shape)

# Visualizza le prime righe dei set
print("\nTrain_w:")
print(train_w.head())
print(train_w.tail())

print("\nTest_w:")
print(test_w.head())
print(test_w.tail())

#verifica di valori 0 o infinito
print(data_w['Close'][data_w['Close'].isna()])
print(data_w['Close'][np.isinf(data_w['Close'])])
print(data_w['Open'][data_w['Open'].isna()])
print(data_w['Open'][np.isinf(data_w['Open'])])

# Gestisci il valore NaN (esempio: imputazione con la media)
data_w['Close'] = data_w['Close'].fillna(data_w['Close'].mean())
data_w['Open'] = data_w['Open'].fillna(data_w['Open'].mean())

# Verifica la correzione
print(data_w['Close'].isna().sum())
print(data_w['Close'].isin([np.inf, -np.inf]).sum())
print(data_w['Open'].isna().sum())
print(data_w['Open'].isin([np.inf, -np.inf]).sum())

for i in lista1:
    adf_test_data_w = adfuller(data_w[i])

    # Estrai i risultati
    statistic = adf_test_data_w[0]
    pvalue = adf_test_data_w[1]
    critical_values = adf_test_data_w[4]

    # Stampa i risultati
    print (f"ADF test {i}")
    print("Statistica ADF:", statistic)
    print("P-value:", pvalue)
    print("Valori critici:", critical_values)
    if pvalue < 0.05:
        print ("stazionario")
    else:
        print ("non stazionario")

for campo in data_w:
    print (campo)
    plot_pacf(data_w[campo], lags=20)
    plt.show()
    plot_acf(data_w[campo], lags=20)
    plt.show()

print ('Close')
modello_arima(train_w['Close'], test_w['Close'], 1, 0, 1)
print ('Open')
modello_arima(train_w['Open'], test_w['Open'], 1, 0, 1)

#arima a intervalli
miglior_modello = modello_arima_iterativo(train_w['Close'], test_w['Close'], p_range, d_range, q_range)
miglior_modello = modello_arima_iterativo(train_w['Open'], test_w['Open'], p_range, d_range, q_range)

"""# analisi modello Close
Il modello ARIMA sembra performare relativamente bene nella previsione di "Close", con bassi valori di RMSE e MAE. Tuttavia, i valori di MPE e MAPE sono "inf", indicando problemi con divisioni per zero nei dati. Questo potrebbe essere dovuto a valori di "Close" molto vicini allo zero.
# analisi modello Open

# Prophet

## preparazione del dataset per prophet
"""

data_w_prophet = pd.DataFrame({
    'ds': df_a['Date'],
    'Close': df_a_trasf['Close'],
    'Open': df_a_trasf['Open']
})
data_w_prophet['ds'] = pd.to_datetime(data_w_prophet['ds'])
# Gestisci il valore NaN (esempio: imputazione con la media)
data_w_prophet['Close'] = data_w_prophet['Close'].fillna(data_w['Close'].mean())
data_w_prophet['Open'] = data_w_prophet['Open'].fillna(data_w['Open'].mean())
# Dividi i dati in train e test set
train_w_prophet, test_w_prophet = train_test_split(data_w_prophet, test_size=0.2, shuffle=False)

train_w_prophet.head

#preparazione del train e test
# Preparazione dei dati per Prophet (Close)
train_w_close = train_w_prophet[['ds', 'Close']].rename(columns={'Close': 'y'})
test_w_close = test_w_prophet[['ds', 'Close']].rename(columns={'Close': 'y'})

# Preparazione dei dati per Prophet (Volume)
train_w_open = train_w_prophet[['ds', 'Open']].rename(columns={'Open': 'y'})
test_w_open = test_w_prophet[['ds', 'Open']].rename(columns={'Open': 'y'})

print ('Open')
# Applica il metodo a train_w_volume e test_w_volume
model_open = modello_prophet(train_w_open, test_w_open)

print ('Close')
# Applica il metodo a train_w_close e test_w_close
model_close = modello_prophet(train_w_close, test_w_close)

"""# Analisi Open

# Analisi Close
I valori di RMSE e MAE sono bassi sia per il set di training che per il set di test, indicando che il modello ha una buona capacità predittiva. Tuttavia, i valori di MPE e MAPE sono "inf", indicando problemi con divisioni per zero nei dati. Questo potrebbe essere dovuto a valori di "Close" molto vicini allo zero. Il modello Prophet sembra essere in grado di prevedere accuratamente i dati di "Close". Tuttavia, è necessario indagare ulteriormente sui dati per capire perché si verificano divisioni per zero. Il grafico delle previsioni mostra che il modello è in grado di catturare la variabilità dei dati. Le componenti del modello (trend e stagionalità) sembrano essere ragionevoli.

# Metodi con dataset non stazionario

## RNN
"""

# Preparazione del dataset usato dati log. per problemi di differenza di distribuzione dei dati tra train e test
close_data = df_w_log['Close'].values.reshape(-1, 1)
open_data = df_w_log['Open'].values.reshape(-1, 1)
#divisione train e test
train_w_rnn_close, test_w_rnn_close = train_test_split(close_data, test_size=0.2, shuffle=False)
train_w_rnn_open, test_w_rnn_open = train_test_split(open_data, test_size=0.2, shuffle=False)

print (train_w_rnn_close)

# Crea il istogrammi
# Appiattisci l'array in un array unidimensionale
train_w_rnn_close_flat = train_w_rnn_close.flatten()
df = pd.DataFrame({'valori': train_w_rnn_close_flat})

# Appiattisci l'array in un array unidimensionale
test_w_rnn_close_flat = test_w_rnn_close.flatten()
df_t = pd.DataFrame({'valori': test_w_rnn_close_flat,})


# Crea gli istogrammi
plt.figure(figsize=(12, 6))  # Imposta la dimensione della figura

plt.subplot(1, 2, 1)  # Crea il primo subplot (1 riga, 2 colonne, posizione 1)
sns.histplot(train_w_rnn_close_flat, bins=30, kde=True)
plt.title('Istogramma Close_train')
plt.xlabel('Valori')
plt.ylabel('Frequenza')

plt.subplot(1, 2, 2)  # Crea il secondo subplot (1 riga, 2 colonne, posizione 2)
sns.histplot(test_w_rnn_close_flat, bins=30, kde=True)
plt.title('Istogramma Close_test')
plt.xlabel('Valori')
plt.ylabel('Frequenza')

plt.tight_layout()  # Aggiusta la spaziatura tra i subplot
plt.show()

# Esempio di utilizzo per la colonna "Close"
print ('CLose')
model_w_close, history_close = modello_rnn(train_w_rnn_close, test_w_rnn_close, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_close.history['loss'], label='Loss (train)')
plt.plot(history_close.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()
# Esempio di utilizzo per la colonna "Open"
print ('Open')
model_w_open, history_open = modello_rnn(train_w_rnn_open, test_w_rnn_open, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_open.history['loss'], label='Loss (train)')
plt.plot(history_open.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()

"""## LSTM"""

# Esempio di utilizzo per la colonna "Close"
print ('CLose')
model_w_close, history_close = modello_lstm(train_w_rnn_close, test_w_rnn_close, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_close.history['loss'], label='Loss (train)')
plt.plot(history_close.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()
# Esempio di utilizzo per la colonna "Open"
print ('Open')
model_w_open, history_open = modello_lstm(train_w_rnn_open, test_w_rnn_open, seq_length=20, epochs=20, learning_rate=0.001)
# Visualizza la funzione di perdita
plt.plot(history_open.history['loss'], label='Loss (train)')
plt.plot(history_open.history['val_loss'], label='Loss (validation)')
plt.title('Funzione di perdita durante l\'addestramento')
plt.xlabel('Epoche')
plt.ylabel('Perdita')
plt.legend()
plt.show()

"""# Sentiment analysis

"""

#per risolvere problemi di codifica del file
with open("walmart_cleaned.csv", "rb") as f:  # Apri il file in modalità binaria ("rb")
    result = chardet.detect(f.read())

encoding = result['encoding']
print(f"Codifica rilevata: {encoding}")

# Caricamento dati
reviews_w = pd.read_csv("walmart_cleaned.csv", encoding="MacRoman", quoting=1)

reviews_w.head

reviews_w.shape

print (reviews_w.columns)

# Istogramma per la colonna 'rating'
plt.figure(figsize=(8, 6))
sns.histplot(reviews_w['rating'], bins=10)
plt.title('Distribuzione dei Rating')
plt.xlabel('Rating')
plt.ylabel('Frequenza')
plt.show()

plt.figure(figsize=(8, 6))
sns.histplot(reviews_w['year'], bins=10)  # kde=True aggiunge la stima della densità di kernel
plt.title('Distribuzione delle Date')
plt.xlabel('Date')
plt.ylabel('Frequenza')
plt.show()

# Informazioni generali sul dataset
print("\nInformazioni sul dataset:")
print(reviews_w.info())

"""# Pre-processing"""

# Applicare la pulizia alla colonna "SentimentText"
reviews_w["review"] = reviews_w["review"].astype(str).apply(clean_text)
reviews_w["review"].head

#nuvola di parole
text = " ".join(review_w['review'])
wordcloud = WordCloud(width=800, height=400, max_words=100, background_color='white', colormap='viridis').generate(text)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

# Filtra reviews
positive_texts = " ".join(reviews_w[reviews_w['rating'] == 1]['review'])+' '.join(reviews_w[reviews_w['rating'] == 2]['review'])
neutral_texts= " ".join(reviews_w[reviews_w['rating'] == 3]['review'])
negative_texts = " ".join(reviews_w[reviews_w['rating'] == 4]['review'])+' '.join(reviews_w[reviews_w['rating'] == 5]['review'])


# Conta le parole più comuni per i testi positivi
top_pos = Counter(positive_texts.split())
top_pos_df = pd.DataFrame(top_pos.most_common(100), columns=['Words', 'Counts'])

# Conta le parole più comuni per i testi positivi
top_neu = Counter(neutral_texts.split())
top_neu_df = pd.DataFrame(top_neu.most_common(100), columns=['Words', 'Counts'])


# Conta le parole più comuni per i testi negativi
top_neg = Counter(negative_texts.split())
top_neg_df = pd.DataFrame(top_neg.most_common(100), columns=['Words', 'Counts'])

# Stampa i risultati
print("Parole più comuni nei testi positivi:")
print(top_pos_df.head())

print("Parole più comuni nei testi neutrali:")
print(top_neu_df.head())

print("\nParole più comuni nei testi negativi:")
print(top_neg_df.head())

fig,ax=plt.subplots(nrows=1,ncols=3,figsize=(15,7.5))
sns.barplot(y='Words',x='Counts',data=top_pos_df[:20],color='deepskyblue',ax=ax[0])
sns.barplot(y='Words',x='Counts',data=top_neu_df[:20],color='green',ax=ax[1])
sns.barplot(y='Words',x='Counts',data=top_neg_df[:20],color='coral',ax=ax[2])
ax[0].set_title("Most Frequent words in Positive review")
ax[1].set_title("Most Frequent words in Neutral review")
ax[2].set_title("Most Frequent words in Negative review")
plt.show()

"""### Criteri empirici"""

# Concatena tutte le recensioni in un'unica stringa
corpus_w = " ".join(reviews_w["review"].tolist())

# Applica la funzione analisi_ttr_hapax all'intero corpus
ttr, percentuale_hapax = analisi_ttr_hapax(corpus_w)

# Stampa i risultati
print("TTR:", ttr)
print("Percentuale di Hapax:", percentuale_hapax)

# 1. Calculate Word Frequencies
tokens = word_tokenize(corpus_w.lower())
word_counts = Counter(tokens)
# 2. Identify Infrequent Words (frequency == 1)
infrequent_words = {word for word, count in word_counts.items() if count == 1}
# 3. Function to remove infrequent words from a single review
def remove_infrequent(text):
    words = word_tokenize(str(text).lower())
    filtered_words = [word for word in words if word not in infrequent_words]
    return " ".join(filtered_words)
# 4. Apply the function to the 'review' column
reviews_w["review_clean"] = reviews_w["review"].astype(str).apply(remove_infrequent)

corpus_w_clean= " ".join(reviews_w["review_clean"].tolist())
# Applica la funzione analisi_ttr_hapax all'intero corpus
ttr_clean, percentuale_hapax_clean = analisi_ttr_hapax(corpus_w_clean)

# Stampa i risultati
print("TTR:", ttr_clean)
print("Percentuale di Hapax:", percentuale_hapax_clean)

#TF
# Crea un oggetto CountVectorizer
vectorizer_w = CountVectorizer()

# Adatta il vectorizer al corpus e trasforma il corpus in una matrice TFM
tf_matrix_w = vectorizer_w.fit_transform([corpus_w])

# Ottieni i nomi delle feature (i termini)
feature_names = vectorizer_w.get_feature_names_out()

# Crea un DataFrame pandas dalla matrice TFM
tf_df_w = pd.DataFrame(tf_matrix_w.toarray(), columns=feature_names)

# Visualizzazione delle Frequenze dei Termini

# Calcola la somma delle frequenze per ogni termine
term_frequencies_w = tf_df_w.sum()

# Boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(x=term_frequencies_w)
plt.title("Distribuzione delle Frequenze dei Termini nel Corpus")
plt.xlabel("Frequenza")
plt.show()

#TF-IDF
# Crea un oggetto TfidfVectorizer
vectorizer_tfidf_w = TfidfVectorizer(max_df=1.0, min_df=1, stop_words='english')

# Adatta il vectorizer al corpus e trasforma il corpus in una matrice TDM
tfidf_matrix_w = vectorizer_tfidf_w.fit_transform(reviews_w["review"])

# Numero di componenti desiderate (argomenti latenti)
n_components = 4  # Puoi regolare questo valore

# Crea un oggetto TruncatedSVD
lsa_w = TruncatedSVD(n_components=n_components)

# Applica LSA alla matrice TF-IDF
lsa_matrix_w= lsa_w.fit_transform(tfidf_matrix_w)

# Ottieni i termini (feature names)
terms_w= vectorizer_tfidf_w.get_feature_names_out()

# Visualizzazione delle Parole per Topic con Grafico a Dispersione (Termini Limitati)
num_terms_to_display = 20  # Puoi regolare questo valore

for i, component in enumerate(lsa_w.components_):
    terms_zipped_ = zip(terms_w, component)
    top_terms_ = sorted(terms_zipped_, key=lambda x: x[1], reverse=True)[:num_terms_to_display]
    terms, scores = zip(*top_terms_)

    plt.figure(figsize=(10, 6))
    plt.scatter(scores, range(len(terms)))
    for j, term in enumerate(terms):
        plt.annotate(term, (scores[j], j))

    plt.title(f"Argomento {i + 1} - Grafico a Dispersione")
    plt.xlabel("Punteggio")
    plt.ylabel("Termini")
    plt.yticks([])  # Rimuovi i tick sull'asse y
    plt.show()

#LDA
# Crea un oggetto CountVectorizer
vectorizer_lda_w = CountVectorizer(max_df=1.0, min_df=1, stop_words='english')

# Adatta il vectorizer al corpus e trasforma il corpus in una matrice DTM
dtm_w = vectorizer_lda_w.fit_transform(reviews_w["review"])

# Numero di argomenti desiderati
n_topics = 3  # Puoi regolare questo valore

# Modifica i parametri alpha e beta
alpha = 0.1  # Puoi regolare questo valore
beta = 0.1  # Puoi regolare questo valore

# Crea un oggetto LatentDirichletAllocation con i parametri modificati
lda_w= LatentDirichletAllocation(n_components=n_topics, random_state=42, doc_topic_prior=alpha, topic_word_prior=beta)

# Applica LDA alla matrice DTM
lda_w.fit(dtm_w)

# Ottieni i termini (feature names)
terms_lda_w = vectorizer_lda_w.get_feature_names_out()

# Stampa i termini più importanti per ogni argomento
for i, topic in enumerate(lda_w.components_):
    terms_zipped = zip(terms_lda_w, topic)
    top_terms = sorted(terms_zipped, key=lambda x: x[1], reverse=True)[:10]  # Ottieni i primi 10 termini
    print(f"Argomento {i + 1}:")
    for term, score in top_terms:
        print(f"  {term}: {score:.4f}")

    # Visualizzazione con Grafico a Barre
    terms, scores = zip(*top_terms)
    plt.figure(figsize=(8, 6))
    sns.barplot(x=list(scores), y=list(terms))
    plt.title(f"Argomento {i + 1}")
    plt.xlabel("Punteggio")
    plt.ylabel("Termini")
    plt.show()

"""# Apprendimento sui specifici topic"""

# 1. Identificazione dei Topic e Assegnazione delle Recensioni
topic_probabilities = lda_w.transform(dtm_w)
reviews_w['topic'] = topic_probabilities.argmax(axis=1)

# 2. Creazione del Dataset Etichettato
data_lda_w = reviews_w[['review', 'topic', 'rating']]

# 3. Preparazione dei Dati per la Classificazione
X_train_w, X_test_w, y_train_w, y_test_w = train_test_split(
    data_lda_w[['review', 'topic']], data_lda_w['rating'], test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer()
X_train_w_review = vectorizer.fit_transform(X_train_w['review'])
X_test_w_review = vectorizer.transform(X_test_w['review'])

X_train_w_topic = pd.get_dummies(X_train_w['topic'], prefix='topic').values
X_test_w_topic = pd.get_dummies(X_test_w['topic'], prefix='topic').values
# Questa riga di codice converte la colonna 'topic' in un array di variabili dummy
# Combina le caratteristiche manualmente
X_train_w_combined = sp.hstack((X_train_w_review, X_train_w_topic))
X_test_w_combined = sp.hstack((X_test_w_review, X_test_w_topic))
#Questa funzione di scipy.sparse è progettata per concatenare matrici sparse e array densi in modo efficiente.

print(y_train_w)
print (X_train_w_review)
print (X_train_w_topic)
print (X_train_w_combined)
print (X_train_w)
print (X_test_w)

"""## Modello Logistic Regression"""

modello_log_reg_w= model_logistic_regression(X_train_w_combined,X_test_w_combined, y_train_w, y_test_w)

"""## Gradient Boosting"""

modello_gb_w= model_gradient_boosting(X_train_w_combined,X_test_w_combined, y_train_w, y_test_w)

"""## Random Forest"""

modello_rf_w= model_random_forest(X_train_w_combined,X_test_w_combined, y_train_w, y_test_w)

